version: "2"
services:
  mysql:
    image: centos/mysql-57-centos7:5.7
    container_name: mysql57
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
