version: '3'
services:
  dev:
#    image: mysql:8.0
    image: mysql:5.7
    container_name: mysqldb
    command: [ "--server-id=1", "--log_bin=mysql-bin" ]
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./mysqlData:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es6
    environment:
      - cluster.name=geektime
      - TZ=Asia/Shanghai
    #      - node.name=es73
    #      - bootstrap.memory_lock=true
    #      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #      - discovery.seed_hosts=es73
    #      - cluster.initial_master_nodes=es73
    #    ulimits:
    #      memlock:
    #        soft: -1
    #        hard: -1
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
