version: '3.1'
services:
  cerebro:
    image: lmenezes/cerebro:0.9.4
    container_name: cerebro73
#    ports:
#      - 9000:9000
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      es73net:
        ipv4_address: "172.19.0.3"
    # 控制启动顺序
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana73
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    volumes:
      - /Users/wangwc/IdeaProjects/docker-compose/all/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      es73net:
        ipv4_address: "172.19.0.4"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es73
    environment:
      - cluster.name=geektime
      - node.name=es73
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es73
      - cluster.initial_master_nodes=es73
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - es73data1:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
    networks:
      es73net:
        ipv4_address: "172.19.0.5"
  rediscluster:
    image: grokzen/redis-cluster:latest
    container_name: redis-cluster73
    environment:
      INITIAL_PORT: 5000
      MASTERS: 3
      SLAVES_PER_MASTER: 1
      TZ: Asia/Shanghai
    networks:
      es73net:
        ipv4_address: "172.19.0.6"
  nginx:
    image: nginx:alpine
    container_name: nginx73
    ports:
      - 5555:80
    volumes:
      - /Users/wangwc/IdeaProjects/docker-compose/all/nginx.conf:/etc/nginx/nginx.conf
    networks:
      es73net:
        ipv4_address: "172.19.0.2"
    environment:
      - TZ=Asia/Shanghai

networks:
  es73net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.0.0/16"

