version: '3.1'
services:
  rediscluster:
    image: grokzen/redis-cluster:latest
    container_name: redis-cluster
    ports:
      - 15000:5000
    environment:
#      SENTINEL: 'true'
      INITIAL_PORT: 5000
      MASTERS: 3
      SLAVES_PER_MASTER: 1
      TZ: Asia/Shanghai
