version: '3.1'
services:
  nginx:
    image: nginx:latest
#    image: nginx:alpine
    container_name: nginx01
    ports:
      - 18080:1443
    volumes:
      - D:\code\java\docker-compose\nginx\httpnginx.conf:/etc/nginx/nginx.conf
      - D:\code\java\docker-compose\nginx\ssl\:/etc/nginx/ssl/
    network_mode: "bridge"
    environment:
      - TZ=Asia/Shanghai