version: '3.1'
services:
  nginx:
    image: nginx:latest
#    image: nginx:alpine
    container_name: nginx01
    ports:
      - 6443:6443
    volumes:
#      - ./stream/map.conf:/etc/nginx/nginx.conf
      - ./nginx0209-ok.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/
    network_mode: "bridge"
    environment:
      - TZ=Asia/Shanghai