version: '3.1'
services:
  nginx:
#    image: nginx:latest
    image: nginx:alpine
    container_name: nginx01
    ports:
      - 8000:80
#    volumes:
#      - /Users/wangwc/IdeaProjects/docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: "bridge"
    environment:
      - TZ=Asia/Shanghai