version: "2"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./data/mysql/:/var/lib/mysql
    ports:
      - "3306:3306"
